---
- name: install nodejs on nodejs server
  hosts: nodejs
  become: true
  tasks:

  - name: get nodejs repository
    shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

  - name: install nodejs
    yum:
      name: nodejs
      state: latest 

  - name: copy index.js from my computer to the nodejs server
    copy:
      src: /home/exam/index.js
      dest: /home/exam/index.js

  - name: copy nodejs unit file
    copy:
      src: /home/exam/node.service
      dest: /etc/systemd/system/node.service
  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes

  - name: ensure nodejs is running and enabled
    service:
      name: node 
      state: started
      enabled: yes  
